CREATE DATABASE c360_analytics;

CREATE TABLE c360_analytics.ga_sessions_analytics
WITH (
  format='PARQUET',
  external_location='s3://c360view-us-west-2-806828409366-analytics/ga/ga_sessions_analytics/',
  partitioned_by=ARRAY['day']
) AS
SELECT
visitorid  ,
visitnumber  ,
visitid  ,
visitstarttime  ,
visitdate  ,
t_visits  ,
t_hits  ,
t_pageviews  ,
t_timeonsite  ,
t_bounces  ,
t_transactions  ,
t_transactionrevenue  ,
t_newvisits  ,
t_screenviews  ,
t_uniquescreenviews  ,
t_timeonscreen  ,
t_totaltransactionrevenue  ,
t_sessionqualitydim  ,
trafficsource_referralpath  ,
trafficsource_campaign  ,
trafficsource_source  ,
trafficsource_medium  ,
trafficsource_keyword  ,
trafficsource_adcontent  ,
adwords_campaignid ,
adwords_adgroupid ,
adwords_creativeid ,
adwords_criteriaid ,
adwords_page ,
adwords_slot ,
adwords_criteriaparameters ,
adwords_gclid ,
adwords_customerid ,
adwords_adnetworktype ,
adwords_targetingcriteria ,
adwords_isvideoad ,
trafficsource_istruedirect  ,
trafficsource_campaigncode ,
device_browser  ,
device_operatingsystem  ,
device_ismobile  ,
device_devicecategory  ,
geonetwork_subcontinent  ,
geonetwork_country  ,
geonetwork_region  ,
geonetwork_metro  ,
geonetwork_city  ,
geonetwork_networkdomain  ,
hit_hitnumber  ,
hit_time  ,
hit_hour  ,
hit_minute  ,
hit_issecure ,
hit_isinteraction  ,
hit_isentrance  ,
hit_isexit  ,
hit_referer ,
hitpage_pagepath ,
hitpage_hostname ,
hitpage_pagetitle ,
hitpage_searchkeyword ,
hitpage_searchcategory ,
hitpage_pagepathlevel1 ,
hitpage_pagepathlevel2 ,
hitpage_pagepathlevel3 ,
hitpage_pagepathlevel4 ,
hit_contentinfo ,
hit_appinfo.screenname as hit_appinfo_screenname,
hit_appinfo.landingscreenname as hit_appinfo_landingscreenname,
hit_appinfo.exitscreenname as hit_appinfo_exitscreenname,
hit_appinfo.screendepth as hit_appinfo_screendepth,
hit_promotionactioninfo ,
hit_refund ,
hit_publisher ,
hit_datasource ,
fullvisitorid ,
userid ,
clientid ,
channelgrouping ,
socialengagementtype ,
day
from "c360_stage"."ga_sessions_split_avro_stg"
