CREATE DATABASE c360_stage;

CREATE TABLE c360_stage.ga_sessions_unnest_hits_avro_stg
WITH (
  format='AVRO',
  external_location='s3://c360view-us-west-2-806828409366-stage/ga/ga_sessions_hits_avro_stg/',
  partitioned_by=ARRAY['day']
) AS
SELECT
    visitorid ,
    visitnumber ,
    visitid ,
    visitstarttime ,
    date visitdate,
    totals.visits as t_visits,
    totals.hits as t_hits,
    totals.pageviews as t_pageviews,
    totals.timeonsite as t_timeonsite,
    totals.bounces as t_bounces,
    totals.transactions as t_transactions,
    totals.transactionrevenue as t_transactionrevenue,
    totals.newvisits as t_newvisits,
    totals.screenviews as t_screenviews,
    totals.uniquescreenviews as t_uniquescreenviews,
    totals.timeonscreen as t_timeonscreen,
    totals.totaltransactionrevenue as t_totaltransactionrevenue,
    totals.sessionqualitydim as t_sessionqualitydim,
    trafficsource.referralpath as trafficsource_referralpath,
    trafficsource.campaign as trafficsource_campaign,
    trafficsource.source as trafficsource_source,
    trafficsource.medium as trafficsource_medium,
    trafficsource.keyword as trafficsource_keyword,
    trafficsource.adcontent as trafficsource_adcontent,
    trafficsource.adwordsclickinfo as trafficsource_adwordsclickinfo,
    trafficsource.istruedirect as trafficsource_istruedirect,
    trafficsource.campaigncode as trafficsource_campaigncode,
    device.browser as device_browser,
    device.operatingsystem as device_operatingsystem,
    device.ismobile as device_ismobile,
    device.devicecategory as device_devicecategory,
    geonetwork.subcontinent as geonetwork_subcontinent,
    geonetwork.country as geonetwork_country,
    geonetwork.region as geonetwork_region,
    geonetwork.metro as geonetwork_metro,
    geonetwork.city as geonetwork_city,
    geonetwork.networkdomain as geonetwork_networkdomain,
    customdimensions,
    hit.hitnumber as hit_hitnumber,
    hit.time as hit_time,
    hit.hour as hit_hour,
    hit.minute as hit_minute,
    hit.issecure as hit_issecure,
    hit.isinteraction as hit_isinteraction,
    hit.isentrance as hit_isentrance,
    hit.isexit as hit_isexit,
    hit.referer as hit_referer,
    hit.page as hit_page,
    hit.transaction as hit_transaction,
    hit.item as hit_item,
    hit.contentinfo as hit_contentinfo,
    hit.appinfo as hit_appinfo,
    hit.exceptioninfo as hit_exceptioninfo,
    hit.eventinfo as hit_eventinfo,
    hit.product as hit_product,
    hit.promotion as hit_promotion,
    hit.promotionactioninfo as hit_promotionactioninfo,
    hit.refund as hit_refund,
    hit.ecommerceaction as hit_ecommerceaction,
    hit.experiment as hit_experiment,
    hit.publisher as hit_publisher,
    hit.customvariables as hit_customvariables,
    hit.customdimensions as hit_customdimensions,
    hit.custommetrics as hit_custommetrics,
    hit.type as hit_socialengagementtype,
    hit.social as hit_social,
    hit.latencytracking as hit_latencytracking,
    hit.sourcepropertyinfo as hit_sourcepropertyinfo,
    hit.contentgroup as hit_contentgroup,
    hit.datasource as hit_datasource,
    hit.publisher_infos as hit_publisher_infos,
    fullvisitorid ,
    userid ,
    clientid ,
    channelgrouping ,
    socialengagementtype,
    date day
FROM "c360_raw"."data"
CROSS JOIN UNNEST (hits) AS h (hit);
