select
    visitorid ,
    visitnumber ,
    visitid ,
    visitstarttime ,
    date as visitdate,
    totals.visits as t_visits,
    totals.hits  as t_hits,
    totals.pageviews as t_pageviews,
    totals.timeonsite as t_timeonsite,
    totals.bounces as t_bounces,
    totals.transactions as t_transactions,
    totals.transactionrevenue as t_transactionrevenue,
    totals.newvisits as t_newvisits,
    totals.screenviews as t_screenviews,
    totals.uniquescreenviews as t_uniquescreenviews,
    totals.timeonscreen as t_timeonscreen,
    totals.totaltransactionrevenue as t_totaltransactionrevenue,
    totals.sessionqualitydim as t_sessionqualitydim,
    trafficsource.referralpath as trafficsource_referralpath,
    trafficsource.campaign as trafficsource_campaign,
    trafficsource.source as trafficsource_source,
    trafficsource.medium as trafficsource_medium,
    trafficsource.keyword as trafficsource_keyword,
    trafficsource.adcontent as trafficsource_adcontent,
    trafficsource.adwordsclickinfo as trafficsource_adwordsclickinfo,
    trafficsource.istruedirect as trafficsource_istruedirect,
    trafficsource.campaigncode as trafficsource_campaigncode,
    device.browser as device_browser,
    device.browserversion as device_browserversion,
    device.browsersize as device_browsersize,
    device.operatingsystem as device_operatingsystem,
    device.operatingsystemversion as device_operatingsystemversion,
    device.ismobile as device_ismobile,
    device.mobiledevicebranding as device_mobiledevicebranding,
    device.mobiledevicemodel as device_mobiledevicemodel,
    device.mobileinputselector as device_mobileinputselector,
    device.mobiledeviceinfo as device_mobiledeviceinfo,
    device.mobiledevicemarketingname as device_mobiledevicemarketingname,
    device.flashversion as device_flashversion,
    device.javaenabled as device_javaenabled,
    device.language as device_language,
    device.screencolors as device_screencolors,
    device.screenresolution as device_screenresolution,
    device.devicecategory as device_devicecategory,
    geonetwork.subcontinent as geonetwork_subcontinent,
    geonetwork.country as geonetwork_country,
    geonetwork.region as geonetwork_region,
    geonetwork.metro as geonetwork_metro,
    geonetwork.city as geonetwork_city,
    geonetwork.cityid as geonetwork_cityid,
    geonetwork.networkdomain as geonetwork_networkdomain,
    geonetwork.latitude as geonetwork_latitude,
    geonetwork.longitude as geonetwork_longitude,
    geonetwork.networklocation as geonetwork_networklocation,
    customdimensions,
    hits,
    fullvisitorid ,
    userid ,
    clientid ,
    channelgrouping ,
    socialengagementtype ,
    partition_0 ,
    partition_1
    from data limit 10;
