CREATE TABLE "c360view_stage"."ga_sessions_split_avro_stg"
WITH (
  format='AVRO',
  external_location='s3://c360view-us-west-2-806828409366-stage/ga/ga_sessions_split_avro_stg/',
  partitioned_by=ARRAY['day']
) AS
SELECT
visitorid  ,
visitnumber  ,
visitid  ,
visitstarttime  ,
visitdate  ,
t_visits  ,
t_hits  ,
t_pageviews  ,
t_timeonsite  ,
t_bounces  ,
t_transactions  ,
t_transactionrevenue  ,
t_newvisits  ,
t_screenviews  ,
t_uniquescreenviews  ,
t_timeonscreen  ,
t_totaltransactionrevenue  ,
t_sessionqualitydim  ,
trafficsource_referralpath  ,
trafficsource_campaign  ,
trafficsource_source  ,
trafficsource_medium  ,
trafficsource_keyword  ,
trafficsource_adcontent  ,
trafficsource_adwordsclickinfo.campaignid as adwords_campaignid,
trafficsource_adwordsclickinfo.adgroupid as adwords_adgroupid,
trafficsource_adwordsclickinfo.creativeid as adwords_creativeid,
trafficsource_adwordsclickinfo.criteriaid as adwords_criteriaid,
trafficsource_adwordsclickinfo.page as adwords_page,
trafficsource_adwordsclickinfo.slot as adwords_slot,
trafficsource_adwordsclickinfo.criteriaparameters as adwords_criteriaparameters,
trafficsource_adwordsclickinfo.gclid as adwords_gclid,
trafficsource_adwordsclickinfo.customerid as adwords_customerid,
trafficsource_adwordsclickinfo.adnetworktype as adwords_adnetworktype,
trafficsource_adwordsclickinfo.targetingcriteria as adwords_targetingcriteria,
trafficsource_adwordsclickinfo.isvideoad as adwords_isvideoad,
trafficsource_istruedirect  ,
trafficsource_campaigncode  ,
device_browser  ,
device_operatingsystem  ,
device_ismobile  ,
device_devicecategory  ,
geonetwork_subcontinent  ,
geonetwork_country  ,
geonetwork_region  ,
geonetwork_metro  ,
geonetwork_city  ,
geonetwork_networkdomain  ,
customdimensions,
hit_hitnumber  ,
hit_time  ,
hit_hour  ,
hit_minute  ,
hit_issecure  ,
hit_isinteraction  ,
hit_isentrance  ,
hit_isexit  ,
hit_referer  ,
hit_page.pagepath as hitpage_pagepath,
hit_page.hostname as hitpage_hostname,
hit_page.pagetitle as hitpage_pagetitle,
hit_page.searchkeyword as hitpage_searchkeyword,
hit_page.searchcategory as hitpage_searchcategory,
hit_page.pagepathlevel1 as hitpage_pagepathlevel1,
hit_page.pagepathlevel2 as hitpage_pagepathlevel2,
hit_page.pagepathlevel3 as hitpage_pagepathlevel3,
hit_page.pagepathlevel4 as hitpage_pagepathlevel4,
hit_transaction,
hit_item.transactionid as hit_item_transactionid,
hit_item.productname as hit_item_productname,
hit_item.productcategory as hit_item_productcategory,
hit_item.productsku as hit_item_productsku,
hit_item.itemquantity as hit_item_itemquantity,
hit_item.itemrevenue as hit_item_itemrevenue,
hit_item.currencycode as hit_item_currencycode,
hit_item.localitemrevenue hit_item_localitemrevenue,
hit_contentinfo  ,
hit_appinfo ,
hit_exceptioninfo,
hit_eventinfo,
hit_product,
hit_promotion,
hit_promotionactioninfo  ,
hit_refund  ,
hit_ecommerceaction,
hit_experiment,
hit_publisher  ,
hit_customvariables,
hit_customdimensions,
hit_custommetrics,
hit_socialengagementtype  ,
hit_social,
hit_latencytracking,
hit_sourcepropertyinfo,
hit_contentgroup,
hit_datasource  ,
hit_publisher_infos,
fullvisitorid  ,
userid  ,
clientid  ,
channelgrouping  ,
socialengagementtype,
day
FROM "c360view_stage"."ga_sessions_unnest_hits_avro_stg"
